from app.models import db, Article

def seed_articles():
    harp = Article(
        user_id=1, seal_id=1, title='Harp Seals: Monitors of Change in Differing Ecosystems', body="Harp seals are the most abundant marine mammal in the north Atlantic. As an ice obligatory predator, they reflect changes in their environment, particularly during a period of climatic change. As the focus of a commercial hunt, a large historic data set exists that can be used to quantify changes. There are three populations of harp seals: White Sea/Barents Sea, Greenland Sea and Northwest Atlantic. The objective of this paper is to review their current status and to identify the factors that are influencing population dynamics in different areas. Although important historically, recent catches have been low and do not appear to be influencing trends in either of the two northeast Atlantic populations. Massive mortalities of White Sea/Barents Sea seals occurred during the mid 1980s due to collapses in their main prey species. Between 2004 and 2006, pup production in this population declined by 2/3 and has remained low. Body condition declined during the same period, suggesting that ecosystem changes may have resulted in reduced reproductive rates, possibly due to reduced prey availability and/or competition with Atlantic cod. The most recent estimate of pup production in the Greenland Sea also suggests a possible decline during a period of reduced hunting although the trend in this population is unclear. Pupping concentrations are closer to the Greenland coast due to the reduction in ice in the traditional area and increased drift may result in young being displaced from their traditional feeding grounds leading to increased mortality. Reduced ice extent and thickness has resulted in major mortality of young in the Northwest Atlantic population in some years. After a period of increase, the population remained relatively stable between 1996 and 2013 due to increased hunting, multiple years with increased ice-related mortality of young seals, and lower reproductive rates. With a reduction in harvest and improved survival of young, the population appears to be increasing although extremely large interannual variations in body condition and fecundity have been observed which were found to be influenced by variations in capelin biomass and ice conditions. Each of these populations has been impacted differently by changes in their ecosystems and hunting practices. By identifying the factors influencing these three populations, we can gain a better understanding of how species may respond to changes that are occurring in their ecosystems."
    )

    leopard = Article(
        user_id=1, seal_id=2, title='Leopard Seals (Hydrurga leptonyx) in New Zealand Waters Predating on Chondrichthyans', body="Leopard seals (Hydrurga leptonyx) are top-order predators that prey on a wide variety of species including crustaceans, cephalopods, fishes, birds, and pinnipeds. While multiple diet studies have been conducted worldwide, there are no previous accounts of leopard seals predating on chondrichthyans. As part of a wider study on the diet of leopard seals in New Zealand (NZ) waters, researchers and citizen scientists recorded 39 observations of predation and collected 127 scats (166 total records) between 1942 and 2019. Predation on chondrichthyans was detected in 23.1% (n = 9) of observations of predation and 7.1% (n = 9) of scats (the latter via morphological examination and DNA sequencing). From both observations of predations and scats, three chondrichthyan species or genus were identified; elephantfish (Callorhinchus milii), ghost sharks (Hydrolagus spp.) and spiny dogfish (Squalus acanthias). While this is the first published record of leopard seals feeding on chondrichthyans, the relatively high frequency of occurrence within our NZ records, and that certain individuals appeared to target this type of prey, indicates that these species could constitute a substantial, or important, part of the diet for some leopard seals in this region. As chondrichthyans form an important part of the NZ marine ecosystems, our recognition of an additional top-order predator of these species contributes to understanding the overall health of, and future impacts of predators on, the wider NZ marine ecosystem."
    )

    db.session.add(harp)
    db.session.add(leopard)

    db.session.commit()

def undo_articles():
    db.session.execute('TRUNCATE users RESTART IDENTITY CASCADE;')
    db.session.commit()
