"""empty message

Revision ID: 27686eb5d605
Revises: 8453c72e5630
Create Date: 2022-09-07 16:04:59.552330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27686eb5d605'
down_revision = '8453c72e5630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'name')
    # ### end Alembic commands ###
