"""empty message

Revision ID: 3fce94348a8b
Revises: 59f821a8d9ff
Create Date: 2022-08-31 15:20:20.499890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fce94348a8b'
down_revision = '59f821a8d9ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seals', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('seals_user_id_key', 'seals', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('seals_user_id_key', 'seals', ['user_id'])
    op.alter_column('seals', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
