"""empty message

Revision ID: 57e50a2b31f4
Revises: 27686eb5d605
Create Date: 2022-09-09 15:50:05.546209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e50a2b31f4'
down_revision = '27686eb5d605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travels', sa.Column('name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travels', 'name')
    # ### end Alembic commands ###
