"""empty message

Revision ID: 8453c72e5630
Revises: 3fce94348a8b
Create Date: 2022-09-01 13:55:49.394990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8453c72e5630'
down_revision = '3fce94348a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'body',
               existing_type=sa.VARCHAR(length=15000),
               nullable=False)
    op.alter_column('locations', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('locations', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('locations', 'description',
               existing_type=sa.VARCHAR(length=10000),
               nullable=False)
    op.alter_column('seals', 'image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('seals', 'description',
               existing_type=sa.VARCHAR(length=10000),
               nullable=False)
    op.alter_column('travels', 'description',
               existing_type=sa.VARCHAR(length=10000),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('travels', 'description',
               existing_type=sa.VARCHAR(length=10000),
               nullable=True)
    op.alter_column('seals', 'description',
               existing_type=sa.VARCHAR(length=10000),
               nullable=True)
    op.alter_column('seals', 'image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('locations', 'description',
               existing_type=sa.VARCHAR(length=10000),
               nullable=True)
    op.alter_column('locations', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('locations', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('articles', 'body',
               existing_type=sa.VARCHAR(length=15000),
               nullable=True)
    # ### end Alembic commands ###
